nowTickとかspeedとかの計算があってるか怪しいです
Oyaki122/musicGame pull request #2
Opened 2020-07-08 13:28 UTC by yi7242

2020-07-08 14:03 UTC, Oyaki122 requested changes
変数名の部分をファイル側にコメントした様に変更してください。
よろしくおねがいします

2020-07-08 14:03 UTC, Oyaki122 commented on position.h
> +int top_to_judge,balls; //上から判定まで届くのにかかる時間、上から判定までの球の数
memo.mdの「球」は電球の球の意味なので、ballsをlights_numとかに変更してください

2020-07-17 15:20 UTC, yi7242 commented
変更しました

2020-08-02 08:23 UTC, Oyaki122 commented
確認が遅れてしまい申し訳ありません
これでOKだと思うのでマージします

2020-08-02 08:23 UTC, merged